# This file created by conda-build 25.4.2
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Apr 28 19:46:10 2025
# ------------------------------------------------

package:
  name: zstandard
  version: 0.23.0
source:
  patches:
    - patches/0001-link-zstd-statically.patch
  sha256: b2d8c62d08e7255f68f7a740bae85b3c9b8e5466baa9cbf7f57f1cde0ac6bc09
  url: https://pypi.org/packages/source/z/zstandard/zstandard-0.23.0.tar.gz
build:
  number: '2'
  string: py312hea69d52_2
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - ca-certificates 2025.4.26 hbd8a1cb_0
    - cctools_osx-64 1010.6 hd19c6af_6
    - cctools_osx-arm64 1010.6 hd9414f1_6
    - cffi 1.17.1 py312hf857d28_0
    - clang 18.1.8 default_h576c50e_9
    - clang-18 18.1.8 default_h3571c67_9
    - clang_impl_osx-arm64 18.1.8 hadf8e89_24
    - clang_osx-arm64 18.1.8 h1728699_24
    - clangxx 18.1.8 default_heb2e8d1_9
    - clangxx_impl_osx-arm64 18.1.8 hd2305f4_24
    - compiler-rt 18.1.8 h1020d70_1
    - compiler-rt_osx-64 18.1.8 hf2b8a54_1
    - cross-python_osx-arm64 3.12 50_cpython
    - crossenv 1.5.0 pyhd8ed1ab_1
    - gettext 0.23.1 hd385c8e_0
    - gettext-tools 0.23.1 h27064b9_0
    - ld64_osx-64 951.9 h33512f0_6
    - ld64_osx-arm64 951.9 h0ae773b_6
    - libasprintf 0.23.1 h27064b9_0
    - libasprintf-devel 0.23.1 h27064b9_0
    - libclang-cpp18.1 18.1.8 default_h3571c67_9
    - libcxx 20.1.3 hf95d169_0
    - libcxx-devel 18.1.8 h7c275be_8
    - libexpat 2.7.0 h240833e_0
    - libffi 3.4.6 h281671d_1
    - libgettextpo 0.23.1 h27064b9_0
    - libgettextpo-devel 0.23.1 h27064b9_0
    - libiconv 1.18 h4b5e92a_1
    - libintl 0.23.1 h27064b9_0
    - libintl-devel 0.23.1 h27064b9_0
    - libllvm18 18.1.8 hc29ff6c_3
    - liblzma 5.8.1 hd471939_0
    - libsqlite 3.49.1 hdb6dae5_2
    - libxml2 2.13.7 h3fbc333_1
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 18.1.8 hc29ff6c_3
    - llvm-tools-18 18.1.8 hc29ff6c_3
    - lz4-c 1.10.0 h240833e_1
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.5.0 hc426f3f_0
    - popt 1.16 h7b079dc_2002
    - pycparser 2.22 pyh29332c3_1
    - python 3.12.10 h9ccd52b_0_cpython
    - python_abi 3.12 7_cp312
    - readline 8.2 h7cca4af_2
    - rsync 3.4.0 hbf82b91_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - tk 8.6.13 h1abcd95_1
    - tzdata 2025b h78e105d_0
    - xxhash 0.8.3 h6e16a3a_0
    - zstd 1.5.6 h915ae27_0
    - zstd-static 1.5.6 h3756106_0
  host:
    - bzip2 1.0.8 h99b78c6_7
    - ca-certificates 2025.4.26 hbd8a1cb_0
    - cffi 1.17.1 py312h0fad829_0
    - libexpat 2.7.0 h286801f_0
    - libffi 3.4.6 h1da3d7d_1
    - liblzma 5.8.1 h39f12f2_0
    - libsqlite 3.49.1 h3f77e49_2
    - libzlib 1.3.1 h8359307_2
    - ncurses 6.5 h5e97a16_3
    - openssl 3.5.0 h81ee809_0
    - pip 25.1 pyh8b19718_0
    - pycparser 2.22 pyh29332c3_1
    - python 3.12.10 hc22306f_0_cpython
    - python_abi 3.12 7_cp312
    - readline 8.2 h1d1bf99_2
    - setuptools 79.0.1 pyhff2d567_0
    - tk 8.6.13 h5083fa2_1
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - zstd 1.5.6 hb46c0d2_0
    - zstd-static 1.5.6 hfade9a2_0
  run:
    - __osx >=11.0
    - cffi >=1.11
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
test:
  commands:
    - pip check
  imports:
    - zstandard
  requires:
    - pip
    - zstd 1.5.7.*
about:
  description: 'This project provides Python bindings for interfacing with the

    Zstandard compression library. A C extension and CFFI interface are

    provided.

    '
  dev_url: https://github.com/indygreg/python-zstandard
  doc_url: https://github.com/indygreg/python-zstandard/blob/master/README.rst#python-zstandard
  home: https://github.com/indygreg/python-zstandard
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Zstandard bindings for Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250428.1.1
  recipe-maintainers:
    - pavelzw
    - rmax
    - xhochy
  remote_url: https://github.com/conda-forge/zstandard-feedstock
  sha: 4fa8f180d8e326f573e476d10db3b8fac064a583
