# This file created by conda-build 25.4.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri May  2 19:39:45 2025
# ------------------------------------------------

package:
  name: charset-normalizer
  version: 3.4.2
source:
  sha256: 5baececa9ecba31eff645232d59845c07aa030f0c81ee70184a90d35099a0e63
  url: https://pypi.org/packages/source/c/charset-normalizer/charset_normalizer-3.4.2.tar.gz
build:
  entry_points:
    - normalizer = charset_normalizer.cli:cli_detect
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/charset-normalizer_1746214863626/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2025.4.26 hbd8a1cb_0
    - ld_impl_linux-64 2.43 h712a8e2_4
    - libexpat 2.7.0 h5888daf_0
    - libffi 3.4.6 h2dba641_1
    - libgcc 14.2.0 h767d61c_2
    - libgcc-ng 14.2.0 h69a702a_2
    - libgomp 14.2.0 h767d61c_2
    - liblzma 5.8.1 hb9d3cd8_0
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.49.1 hee588c1_2
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.0 h7b32b05_0
    - pip 25.1 pyh8b19718_0
    - python 3.9.22 h85ef794_1_cpython
    - readline 8.2 h8c095d6_2
    - setuptools 80.1.0 pyhff2d567_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - python >=3.9
test:
  commands:
    - pip check
    - normalizer --help
  imports:
    - charset_normalizer
  requires:
    - pip
    - python 3.9.*
about:
  home: https://github.com/Ousret/charset_normalizer
  license: MIT
  license_file:
    - LICENSE
    - data/NOTICE.md
  summary: The Real First Universal Charset Detector. Open, modern and actively maintained
    alternative to Chardet.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250502.2.1
  recipe-maintainers:
    - ocefpaf
  remote_url: https://github.com/conda-forge/charset-normalizer-feedstock
  sha: 207497c0977f129f40536128705e7e7033c40bcd
