# This file created by conda-build 25.3.2
# ------------------------------------------------

package:
  name: simdjson
  version: 3.12.3
source:
  sha256: d0af071f2f4187d8b26b556e83ef832b634bd5feb4e2f537b9dabbd334d4e334
  url: https://github.com/simdjson/simdjson/archive/v3.12.3.tar.gz
build:
  number: 0
  run_exports:
    - simdjson >=3.12.3,<3.13.0a0
  string: ha393de7_0
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - c-ares 1.34.4 hf13058a_0
    - ca-certificates 2025.1.31 h8857fd0_0
    - cctools_osx-64 1010.6 hd19c6af_4
    - cctools_osx-arm64 1010.6 hd9414f1_4
    - clang 18.1.8 default_h576c50e_8
    - clang-18 18.1.8 default_h3571c67_8
    - clang_impl_osx-arm64 18.1.8 hadf8e89_24
    - clang_osx-arm64 18.1.8 h1728699_24
    - clangxx 18.1.8 default_heb2e8d1_8
    - clangxx_impl_osx-arm64 18.1.8 hd2305f4_24
    - clangxx_osx-arm64 18.1.8 h1728699_24
    - cmake 4.0.0 h477996e_0
    - compiler-rt 18.1.8 h1020d70_1
    - compiler-rt_osx-64 18.1.8 hf2b8a54_1
    - icu 75.1 h120a0e1_0
    - krb5 1.21.3 h37d8d59_0
    - ld64_osx-64 951.9 h33512f0_4
    - ld64_osx-arm64 951.9 h0ae773b_4
    - libclang-cpp18.1 18.1.8 default_h3571c67_8
    - libcurl 8.13.0 h5dec5d8_0
    - libcxx 20.1.2 hf95d169_0
    - libcxx-devel 18.1.8 h7c275be_8
    - libedit 3.1.20250104 pl5321ha958ccf_0
    - libev 4.33 h10d778d_2
    - libexpat 2.7.0 h240833e_0
    - libiconv 1.18 h4b5e92a_1
    - libllvm18 18.1.8 hc29ff6c_3
    - liblzma 5.6.4 hd471939_0
    - libnghttp2 1.64.0 hc7306c3_0
    - libssh2 1.11.1 h3dc7d44_0
    - libuv 1.50.0 h4cb831e_0
    - libxml2 2.13.7 hebb159f_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 18.1.8 hc29ff6c_3
    - llvm-tools-18 18.1.8 hc29ff6c_3
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - ncurses 6.5 h0622a9a_3
    - ninja 1.12.1 h3c5361c_0
    - openssl 3.4.1 hc426f3f_0
    - rhash 1.4.5 ha44c9a9_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.7 h8210216_2
  host:
    - libcxx 20.1.2 ha82da77_0
  run:
    - __osx >=11.0
    - libcxx >=18
test:
  commands:
    - test -f "${PREFIX}/include/simdjson.h"
    - test -f "${PREFIX}/lib/libsimdjson${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/cmake/simdjson/simdjson-config.cmake"
    - cmake -G Ninja -S test/ -B build/ -D TEST_TARGET=simdjson ${CMAKE_ARGS}
    - cmake --build build/
    - cmake --build build --target test
  files:
    - test/*
  requires:
    - clangxx_osx-arm64 18.*
    - cmake
    - ninja
about:
  description: 'JSON is everywhere on the Internet.

    Servers spend a *lot* of time parsing it. We need a fresh approach.

    The simdjson library uses commonly available SIMD instructions and

    microparallel algorithms to parse JSON 2.5x faster than anything else out there.

    '
  dev_url: https://github.com/simdjson/simdjson/
  doc_url: https://simdjson.github.io/simdjson/
  home: https://simdjson.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: Parsing gigabytes of JSON per second
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250403.2.1
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - elbaro
  remote_url: https://github.com/conda-forge/simdjson-feedstock
  sha: 8a1f70ea7fc2a04cfe30c858ce1c86d845c6e78d
