# This file created by conda-build 25.5.0
# ------------------------------------------------

package:
  name: libsqlite
  version: 3.50.3
source:
  url: https://www.sqlite.org/2025/sqlite-autoconf-3500300.tar.gz
  sha256: ec5496cdffbc2a4adb59317fd2bf0e582bf0e6acd8f4aae7e97bc723ddba7233
build:
  run_exports:
    - libsqlite >=3.50.3,<4.0a0
  number: 1
  string: h4237e3c_1
requirements:
  build:
    - ca-certificates 2025.7.14 hbd8a1cb_0
    - cctools_osx-64 1021.4 haa85c18_1
    - cctools_osx-arm64 1021.4 h65996a6_1
    - clang 19.1.7 default_h576c50e_3
    - clang-19 19.1.7 default_h3571c67_3
    - clang_impl_osx-arm64 19.1.7 h4fa02b8_25
    - clang_osx-arm64 19.1.7 h1728699_25
    - compiler-rt 19.1.7 h52031e2_0
    - compiler-rt_osx-64 19.1.7 hc6f8467_0
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 954.16 hf1c22e8_1
    - ld64_osx-arm64 954.16 h59013cd_1
    - libclang-cpp19.1 19.1.7 default_h3571c67_3
    - libcxx 20.1.8 h3d58e20_1
    - libiconv 1.18 h4b5e92a_1
    - libllvm19 19.1.7 hc29ff6c_1
    - liblzma 5.8.1 hd471939_2
    - libxml2 2.13.8 h93c44a6_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 19.1.7 h3fe3016_1
    - llvm-tools-19 19.1.7 he90a8e3_1
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.5.1 hc426f3f_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.7 h8210216_2
  host:
    - icu 75.1 hfee45f7_0
    - libzlib 1.3.1 h8359307_2
    - zlib 1.3.1 h8359307_2
  run:
    - __osx >=11.0
    - icu >=75.1,<76.0a0
    - libzlib >=1.3.1,<2.0a0
test:
  commands:
    - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libsqlite3.a
    - test -f $PREFIX/include/sqlite3.h
    - test -f $PREFIX/include/sqlite3ext.h
    - test -f $PREFIX/lib/pkgconfig/sqlite3.pc
about:
  home: http://www.sqlite.org/
  license: blessing
  license_url: http://www.sqlite.org/copyright.html
  summary: Implements a self-contained, zero-configuration, SQL database engine
  description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

    public-domain, SQL database engine.It is the most used database engine

    in the world.

    '
  doc_url: http://www.sqlite.org/docs.html
  doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
  dev_url: https://github.com/mackyle/sqlite
extra:
  recipe-maintainers:
    - flaviomartins
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250723.1.1
  remote_url: https://github.com/conda-forge/sqlite-feedstock
  sha: b64dc1052e960a69eb9504ca42c4fed4ff231f42
