# This file created by conda-build 25.5.0
# ------------------------------------------------

package:
  name: liblzma
  version: 5.8.1
source:
  url: https://github.com/tukaani-project/xz/releases/download/v5.8.1/xz-5.8.1.tar.gz
  sha256: 507825b599356c10dca1cd720c9d0d0c9d5400b9de300af00e4d1ea150795543
build:
  run_exports:
    - liblzma >=5.8.1,<6.0a0
  number: 2
  string: h39f12f2_2
requirements:
  build:
    - clang_bootstrap_osx-arm64 18.1.8 hf1725c4_25
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
  run_constrained:
    - xz 5.8.1.*
  host:
    - __osx >=11.0
  run:
    - __osx >=11.0
test:
  commands:
    - test ! -f ${PREFIX}/lib/liblzma.a
    - test ! -f ${PREFIX}/lib/liblzma${SHLIB_EXT}
    - test -f ${PREFIX}/lib/liblzma.*.dylib
about:
  home: http://tukaani.org/xz/
  dev_url: http://git.tukaani.org/
  summary: a compression library with an API similar to that of zlib
  license: 0BSD
  license_file:
    - COPYING
    - COPYING.0BSD
extra:
  recipe-maintainers:
    - mingwandroid
    - msarahan
    - nehaljwani
    - ocefpaf
    - scopatz
    - xhochy
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250606.2.1
  remote_url: https://github.com/conda-forge/xz-feedstock
  sha: 86438a1d2bb4ba8a6e6c8cbb4add9c33b8110f64
