# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jun 18 18:28:13 2025
# ------------------------------------------------

package:
  name: urllib3
  version: 2.5.0
source:
  url: https://pypi.org/packages/source/u/urllib3/urllib3-2.5.0.tar.gz
  sha256: 3fc47733c7e419d4bc3f6b3dc2b4f890bb743906a30d56ba4a5bfa4bbff92760
build:
  number: '0'
  noarch: python
  script: /home/conda/feedstock_root/build_artifacts/urllib3_1750271362675/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2025.6.15 hbd8a1cb_0
    - editables 0.5 pyhd8ed1ab_1
    - hatch-vcs 0.4.0 pyhd8ed1ab_1
    - hatchling 1.27.0 pypyhd8ed1ab_0
    - importlib-metadata 8.7.0 pyhe01879c_1
    - ld_impl_linux-64 2.43 h1423503_5
    - libexpat 2.7.0 h5888daf_0
    - libffi 3.4.6 h2dba641_1
    - libgcc 15.1.0 h767d61c_2
    - libgcc-ng 15.1.0 h69a702a_2
    - libgomp 15.1.0 h767d61c_2
    - liblzma 5.8.1 hb9d3cd8_2
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.50.1 hee588c1_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.0 h7b32b05_1
    - packaging 25.0 pyh29332c3_1
    - pathspec 0.12.1 pyhd8ed1ab_1
    - pip 25.1.1 pyh8b19718_0
    - pluggy 1.6.0 pyhd8ed1ab_0
    - python 3.9.23 hc30ae73_0_cpython
    - readline 8.2 h8c095d6_2
    - setuptools 80.9.0 pyhff2d567_0
    - setuptools-scm 8.3.1 pyhd8ed1ab_0
    - tk 8.6.13 noxft_hd72426e_102
    - tomli 2.2.1 pyhd8ed1ab_1
    - trove-classifiers 2025.5.9.12 pyhd8ed1ab_0
    - typing-extensions 4.14.0 h32cad80_0
    - typing_extensions 4.14.0 pyhe01879c_0
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - zipp 3.23.0 pyhd8ed1ab_0
  run:
    - brotli-python >=1.0.9
    - h2 >=4,<5
    - pysocks >=1.5.6,<2.0,!=1.5.7
    - python >=3.9
    - zstandard >=0.18.0
test:
  imports:
    - urllib3
    - urllib3.contrib
    - urllib3.util
  commands:
    - pip check
  requires:
    - pip
    - python 3.9.*
about:
  home: https://urllib3.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: HTTP library with thread-safe connection pooling, file post, and more.
  doc_url: https://urllib3.readthedocs.io/
  dev_url: https://github.com/shazow/urllib3
extra:
  recipe-maintainers:
    - illia-v
    - ocefpaf
    - pquentin
    - sethmlarson
    - shazow
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250618.3.1
  remote_url: https://github.com/conda-forge/urllib3-feedstock
  sha: 92f4121a0f5113993625e8a114e5759548304948
