# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Jun  9 14:37:33 2025
# ------------------------------------------------

package:
  name: ruamel.yaml
  version: 0.18.14
source:
  url: https://pypi.org/packages/source/r/ruamel.yaml/ruamel.yaml-0.18.14.tar.gz
  sha256: 7227b76aaec364df15936730efbf7d72b30c0b79b1d578bbb8e3dcb2d81f52b7
build:
  number: '0'
  script: /Users/runner/miniforge3/conda-bld/ruamel.yaml_1749480012856/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install . --no-deps -vv
  script_env:
    - RUAMEL_NO_LONG_DESCRIPTION=1
  string: py312hea69d52_0
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - ca-certificates 2025.4.26 hbd8a1cb_0
    - cctools_osx-64 1010.6 hd19c6af_6
    - cctools_osx-arm64 1010.6 hd9414f1_6
    - clang 18.1.8 default_h576c50e_10
    - clang-18 18.1.8 default_h3571c67_10
    - clang_impl_osx-arm64 18.1.8 hadf8e89_25
    - clang_osx-arm64 18.1.8 h1728699_25
    - clangxx 18.1.8 default_heb2e8d1_10
    - clangxx_impl_osx-arm64 18.1.8 hd2305f4_25
    - compiler-rt 18.1.8 h1020d70_1
    - compiler-rt_osx-64 18.1.8 hf2b8a54_1
    - cross-python_osx-arm64 3.12 51_cpython
    - crossenv 1.5.0 pyhd8ed1ab_1
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 951.9 h33512f0_6
    - ld64_osx-arm64 951.9 h0ae773b_6
    - libclang-cpp18.1 18.1.8 default_h3571c67_10
    - libcxx 20.1.6 hf95d169_0
    - libcxx-devel 18.1.8 h7c275be_8
    - libexpat 2.7.0 h240833e_0
    - libffi 3.4.6 h281671d_1
    - libiconv 1.18 h4b5e92a_1
    - libintl 0.24.1 h27064b9_0
    - libllvm18 18.1.8 default_h3571c67_5
    - liblzma 5.8.1 hd471939_2
    - libsqlite 3.50.1 hdb6dae5_0
    - libxml2 2.14.3 h8c082e5_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 18.1.8 default_h3571c67_5
    - llvm-tools-18 18.1.8 default_h3571c67_5
    - lz4-c 1.10.0 h240833e_1
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.5.0 hc426f3f_1
    - popt 1.16 h7b079dc_2002
    - python 3.12.11 h9ccd52b_0_cpython
    - readline 8.2 h7cca4af_2
    - rsync 3.4.1 hf2bfba0_2
    - sed 4.9 hf9b2955_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - tk 8.6.13 hf689a15_2
    - tzdata 2025b h78e105d_0
    - xxhash 0.8.3 h13e91ac_0
    - zstd 1.5.7 h8210216_2
  host:
    - bzip2 1.0.8 h99b78c6_7
    - ca-certificates 2025.4.26 hbd8a1cb_0
    - libexpat 2.7.0 h286801f_0
    - libffi 3.4.6 h1da3d7d_1
    - liblzma 5.8.1 h39f12f2_2
    - libsqlite 3.50.1 h3f77e49_0
    - libzlib 1.3.1 h8359307_2
    - ncurses 6.5 h5e97a16_3
    - openssl 3.5.0 h81ee809_1
    - pip 25.1.1 pyh8b19718_0
    - python 3.12.11 hc22306f_0_cpython
    - python_abi 3.12 7_cp312
    - readline 8.2 h1d1bf99_2
    - ruamel 1.0 py312h81bd7bf_9
    - setuptools 80.9.0 pyhff2d567_0
    - tk 8.6.13 h892fb3f_2
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - __osx >=11.0
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
    - ruamel.yaml.clib >=0.1.2
test:
  imports:
    - ruamel.yaml
about:
  home: https://sourceforge.net/p/ruamel-yaml
  license: MIT
  license_file: LICENSE
  summary: A YAML package for Python. It is a derivative of Kirill Simonov's PyYAML
    3.11 which supports YAML1.1
extra:
  recipe-maintainers:
    - davidbrochart
    - jakirkham
    - mbargull
    - mwcraig
    - ocefpaf
    - pelson
    - xhochy
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250609.2.1
  remote_url: https://github.com/conda-forge/ruamel.yaml-feedstock
  sha: c485526d1e5e7340363fdefdd5f77c87d637ada1
