# This file created by conda-build 25.4.2
# ------------------------------------------------

package:
  name: libssh2
  version: 1.11.1
source:
  sha256: d9ec76cbe34db98eec3539fe2c899d26b0c837cb3eb466a56b0f109cabf658f7
  url: https://www.libssh2.org/download/libssh2-1.11.1.tar.gz
build:
  number: 0
  run_exports:
    - libssh2 >=1.11.1,<2.0a0
  string: h1590b86_0
requirements:
  build:
    - ca-certificates 2025.1.31 hbd8a1cb_1
    - cctools_osx-arm64 1010.6 hc03f29f_6
    - clang_bootstrap_osx-arm64 11.1.0 h169cfcd_7
    - cmake-no-system 4.0.1 hbcac03e_0
    - ld64_osx-arm64 951.9 hb5a5ce2_6
    - libcxx 20.1.3 hf95d169_0
    - libiconv 1.18 h4b5e92a_1
    - libllvm20 20.1.3 h29c3a6c_0
    - liblzma 5.8.1 hd471939_0
    - libxml2 2.13.7 h3fbc333_1
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 20.1.3 h3fe3016_0
    - llvm-tools-20 20.1.3 he90a8e3_0
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.5.0 hc426f3f_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.7 h8210216_2
  host:
    - ca-certificates 2025.1.31 hbd8a1cb_1
    - libzlib 1.3.1 h8359307_2
    - openssl 3.5.0 h81ee809_0
    - zlib 1.3.1 h8359307_2
  run:
    - libzlib >=1.3.1,<2.0a0
    - openssl >=3.5.0,<4.0a0
test:
  commands:
    - test -f $PREFIX/include/libssh2.h
    - test -f $PREFIX/include/libssh2_publickey.h
    - test -f $PREFIX/include/libssh2_sftp.h
    - test ! -f $PREFIX/lib/libssh2.a
    - test -f $PREFIX/lib/libssh2${SHLIB_EXT}
about:
  description: 'libssh2 is a library implementing the SSH2 protocol, available under
    the revised BSD license.

    '
  dev_url: https://github.com/libssh2/libssh2
  home: https://www.libssh2.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: the SSH library
extra:
  copy_test_source_files: true
  feedstock-name: libssh2
  final: true
  flow_run_id: azure_20250425.1.1
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
    - shadowwalkersb
    - xhochy
  remote_url: https://github.com/conda-forge/libssh2-feedstock
  sha: 95918f87032ee91e796cc3ec4ea9bff4ce98b2b1
