# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sat Jul 26 16:09:42 2025
# ------------------------------------------------

package:
  name: menuinst
  version: 2.3.1
source:
  url: https://github.com/conda/menuinst/archive/2.3.1.tar.gz
  sha256: aaf1b141b78c3f193a968e01ea8ba8a9d25ab08c938f326437114fe108871280
build:
  number: '0'
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION=2.3.1
  script:
    - /Users/runner/miniforge3/conda-bld/menuinst_1753546295087/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
      -m pip install . -vv
  string: py312h81bd7bf_0
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - ca-certificates 2025.7.14 hbd8a1cb_0
    - cctools_osx-64 1021.4 h9667cbc_1
    - cctools_osx-arm64 1021.4 h0198a76_1
    - clang 20.1.8 default_hb6a0502_0
    - clang-20 20.1.8 default_hd2a208e_0
    - clang_impl_osx-arm64 20.1.8 h60ba235_25
    - clang_osx-arm64 20.1.8 h1728699_25
    - clangxx 20.1.8 default_h4c96677_0
    - clangxx_impl_osx-arm64 20.1.8 h957c430_25
    - compiler-rt 20.1.8 h6456c34_0
    - compiler-rt_osx-64 20.1.8 hf09ce48_0
    - cross-python_osx-arm64 3.12 51_cpython
    - crossenv 1.5.0 pyhd8ed1ab_1
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 954.16 h19d01cd_1
    - ld64_osx-arm64 954.16 h37bbaaf_1
    - libclang-cpp20.1 20.1.8 default_hd2a208e_0
    - libcxx 20.1.8 h3d58e20_1
    - libcxx-devel 20.1.8 h7c275be_1
    - libexpat 2.7.1 h21dd04a_0
    - libffi 3.4.6 h281671d_1
    - libiconv 1.18 h4b5e92a_1
    - libintl 0.25.1 h3184127_1
    - libllvm20 20.1.8 h9b4ebcc_0
    - liblzma 5.8.1 hd471939_2
    - libsqlite 3.50.3 h875aaf5_1
    - libxml2 2.13.8 h93c44a6_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 20.1.8 hc040464_0
    - llvm-tools-20 20.1.8 h0167baa_0
    - lz4-c 1.10.0 h240833e_1
    - ncurses 6.5 h0622a9a_3
    - openssl 3.5.1 hc426f3f_0
    - popt 1.16 h7b079dc_2002
    - python 3.12.11 h9ccd52b_0_cpython
    - readline 8.2 h7cca4af_2
    - rsync 3.4.1 hf2bfba0_2
    - sed 4.9 hf9b2955_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - tk 8.6.13 hf689a15_2
    - tzdata 2025b h78e105d_0
    - xxhash 0.8.3 h13e91ac_0
    - zstd 1.5.7 h8210216_2
  host:
    - bzip2 1.0.8 h99b78c6_7
    - ca-certificates 2025.7.14 hbd8a1cb_0
    - icu 75.1 hfee45f7_0
    - importlib-metadata 8.7.0 pyhe01879c_1
    - libexpat 2.7.1 hec049ff_0
    - libffi 3.4.6 h1da3d7d_1
    - liblzma 5.8.1 h39f12f2_2
    - libsqlite 3.50.3 h4237e3c_1
    - libzlib 1.3.1 h8359307_2
    - ncurses 6.5 h5e97a16_3
    - openssl 3.5.1 h81ee809_0
    - packaging 25.0 pyh29332c3_1
    - pip 25.1.1 pyh8b19718_0
    - python 3.12.11 hc22306f_0_cpython
    - readline 8.2 h1d1bf99_2
    - setuptools 80.9.0 pyhff2d567_0
    - setuptools-scm 8.3.1 pyhd8ed1ab_0
    - setuptools_scm 8.3.1 hd8ed1ab_0
    - tk 8.6.13 h892fb3f_2
    - tomli 2.2.1 pyhd8ed1ab_1
    - typing-extensions 4.14.1 h4440ef1_0
    - typing_extensions 4.14.1 pyhe01879c_0
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - zipp 3.23.0 pyhd8ed1ab_0
  run:
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
test:
  imports:
    - menuinst
    - menuinst.api
  commands:
    - SP_DIR="$(python -c 'import site; print(site.getsitepackages()[0])')"
    - test -f "${SP_DIR}/menuinst/data/appkit_launcher_arm64"
    - test -f "${SP_DIR}/menuinst/data/appkit_launcher_x86_64"
    - test -f "${SP_DIR}/menuinst/data/osx_launcher_arm64"
    - test -f "${SP_DIR}/menuinst/data/osx_launcher_x86_64"
about:
  home: https://github.com/conda/menuinst/
  license: BSD-3-Clause AND MIT
  license_file:
    - LICENSE.txt
    - menuinst/_vendor/apipkg/LICENSE
  summary: cross platform install of menu items
  doc_url: https://conda.github.io/menuinst/
extra:
  recipe-maintainers:
    - carlodri
    - goanpeca
    - isuruf
    - jaimergp
    - jakirkham
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250726.1.1
  remote_url: https://github.com/conda-forge/menuinst-feedstock
  sha: f969fef8ac70ffe4fbed2213cf22a6790fe84e63
