# This file created by conda-build 25.5.0
# ------------------------------------------------

package:
  name: libcurl
  version: 8.14.1
source:
  url: http://curl.haxx.se/download/curl-8.14.1.tar.bz2
  sha256: 5760ed3c1a6aac68793fc502114f35c3e088e8cd5c084c2d044abdf646ee48fb
build:
  run_exports:
    - libcurl >=8.14.1,<9.0a0
  number: 0
  string: h73640d1_0
requirements:
  build:
    - ca-certificates 2025.4.26 hbd8a1cb_0
    - cctools_osx-64 1010.6 hd19c6af_6
    - cctools_osx-arm64 1010.6 hd9414f1_6
    - clang 18.1.8 default_h576c50e_10
    - clang-18 18.1.8 default_h3571c67_10
    - clang_impl_osx-arm64 18.1.8 hadf8e89_25
    - clang_osx-arm64 18.1.8 h1728699_25
    - clangxx 18.1.8 default_heb2e8d1_10
    - compiler-rt 18.1.8 h1020d70_1
    - compiler-rt_osx-64 18.1.8 hf2b8a54_1
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 951.9 h33512f0_6
    - ld64_osx-arm64 951.9 h0ae773b_6
    - libclang-cpp18.1 18.1.8 default_h3571c67_10
    - libcxx 20.1.6 hf95d169_0
    - libcxx-devel 18.1.8 h7c275be_8
    - libiconv 1.18 h4b5e92a_1
    - libllvm18 18.1.8 default_h3571c67_5
    - liblzma 5.8.1 hd471939_1
    - libxml2 2.14.3 h8c082e5_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 18.1.8 default_h3571c67_5
    - llvm-tools-18 18.1.8 default_h3571c67_5
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.5.0 hc426f3f_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.7 h8210216_2
  host:
    - c-ares 1.34.5 h5505292_0
    - ca-certificates 2025.4.26 hbd8a1cb_0
    - krb5 1.21.3 h237132a_0
    - libcxx 20.1.6 ha82da77_0
    - libedit 3.1.20250104 pl5321hafb1f1b_0
    - libev 4.33 h93a5062_2
    - libnghttp2 1.64.0 h6d7220d_0
    - libssh2 1.11.1 h1590b86_0
    - libzlib 1.3.1 h8359307_2
    - ncurses 6.5 h5e97a16_3
    - openssl 3.5.0 h81ee809_1
    - zlib 1.3.1 h8359307_2
    - zstd 1.5.7 h6491c7d_2
  run:
    - __osx >=11.0
    - krb5 >=1.21.3,<1.22.0a0
    - libnghttp2 >=1.64.0,<2.0a0
    - libssh2 >=1.11.1,<2.0a0
    - libzlib >=1.3.1,<2.0a0
    - openssl >=3.5.0,<4.0a0
    - zstd >=1.5.7,<1.6.0a0
test:
  commands:
    - curl-config --features
    - curl-config --protocols
    - test -f ${PREFIX}/lib/libcurl${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libcurl.a
    - CURL_SSL_BACKENDS=$(curl-config --ssl-backends)
    - if ! echo $CURL_SSL_BACKENDS | grep -q "OpenSSL"; then exit 1; fi
    - if ! echo $CURL_SSL_BACKENDS | grep -q "Secure Transport"; then exit 1; fi
about:
  home: http://curl.haxx.se/
  license: curl
  license_family: MIT
  license_file: COPYING
  summary: tool and library for transferring data with URL syntax
  description: 'Curl is an open source command line tool and library for transferring
    data

    with URL syntax. It is used in command lines or scripts to transfer data.

    '
  doc_url: https://curl.haxx.se/docs/
  dev_url: https://github.com/curl/curl
  doc_source_url: https://github.com/curl/curl/tree/master/docs
extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - xylar
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250604.2.1
  remote_url: https://github.com/conda-forge/curl-feedstock
  sha: 6dc1ed3d5de0175deaa1445098f8ab8fd0b77875
