# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jun  9 19:40:35 2025
# ------------------------------------------------

package:
  name: requests
  version: 2.32.4
source:
  url: https://pypi.org/packages/source/r/requests/requests-2.32.4.tar.gz
  sha256: 27d0316682c8a29834d3264820024b62a36942083d52caf2f14c0591336d3422
build:
  number: '0'
  noarch: python
  script: /home/conda/feedstock_root/build_artifacts/requests_1749498106507/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2025.4.26 hbd8a1cb_0
    - ld_impl_linux-64 2.43 h712a8e2_4
    - libexpat 2.7.0 h5888daf_0
    - libffi 3.4.6 h2dba641_1
    - libgcc 15.1.0 h767d61c_2
    - libgcc-ng 15.1.0 h69a702a_2
    - libgomp 15.1.0 h767d61c_2
    - liblzma 5.8.1 hb9d3cd8_2
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.50.1 hee588c1_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.0 h7b32b05_1
    - pip 25.1.1 pyh8b19718_0
    - python 3.9.23 hc30ae73_0_cpython
    - readline 8.2 h8c095d6_2
    - setuptools 80.9.0 pyhff2d567_0
    - tk 8.6.13 noxft_hd72426e_102
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - certifi >=2017.4.17
    - charset-normalizer >=2,<4
    - idna >=2.5,<4
    - python >=3.9
    - urllib3 >=1.21.1,<3
  run_constrained:
    - chardet >=3.0.2,<6
test:
  requires:
    - pip
    - python 3.9.*
  commands:
    - pip check
  imports:
    - requests
about:
  home: http://python-requests.org
  license: Apache-2.0
  license_file: LICENSE
  summary: "Requests is an elegant and simple HTTP library for Python, built with\
    \ \u2665."
  dev_url: https://github.com/psf/requests
extra:
  recipe-maintainers:
    - carlodri
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - sigmavirus24
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250609.2.1
  remote_url: https://github.com/conda-forge/requests-feedstock
  sha: 85461680234217ff28c7a06ea946c62d3cd75ece
