# This file created by conda-build 25.3.1
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Mar 31 15:18:21 2025
# ------------------------------------------------

package:
  name: libffi
  version: 3.4.6
source:
  patches:
    - 0001-arm64-use-a-dedicated-dylib-for-trampolines-so-it-ca.patch
    - 0002-Add-support-for-ffi_find_closure_for_code_np-on-Appl.patch
  sha256: b0dea9df23c863a7a50e825440f3ebffabd65df1497108e5d437747843895a4e
  url: https://github.com/libffi/libffi/releases/download/v3.4.6/libffi-3.4.6.tar.gz
build:
  number: '1'
  run_exports:
    - libffi >=3.4.6,<3.5.0a0
  string: h1da3d7d_1
requirements:
  build:
    - autoconf 2.71 pl5321hed12c24_1
    - automake 1.16.5 pl5321h694c41f_0
    - ca-certificates 2025.1.31 h8857fd0_0
    - cctools_osx-64 1010.6 hd19c6af_4
    - cctools_osx-arm64 1010.6 hd9414f1_4
    - clang 18.1.8 default_h576c50e_8
    - clang-18 18.1.8 default_h3571c67_8
    - clang_impl_osx-arm64 18.1.8 hadf8e89_24
    - clang_osx-arm64 18.1.8 h1728699_24
    - clangxx 18.1.8 default_heb2e8d1_8
    - compiler-rt 18.1.8 h1020d70_1
    - compiler-rt_osx-64 18.1.8 hf2b8a54_1
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 951.9 h33512f0_4
    - ld64_osx-arm64 951.9 h0ae773b_4
    - libclang-cpp18.1 18.1.8 default_h3571c67_8
    - libcxx 20.1.1 hf95d169_0
    - libcxx-devel 18.1.8 h7c275be_8
    - libiconv 1.18 h4b5e92a_1
    - libllvm18 18.1.8 hc29ff6c_3
    - libltdl 2.4.3a h240833e_0
    - liblzma 5.6.4 hd471939_0
    - libtool 2.5.4 h240833e_0
    - libxml2 2.13.7 hebb159f_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 18.1.8 hc29ff6c_3
    - llvm-tools-18 18.1.8 hc29ff6c_3
    - m4 1.4.18 haf1e3a3_1001
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.4.1 hc426f3f_0
    - patch 2.7.6 hbcf498f_1002
    - perl 5.32.1 7_h10d778d_perl5
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - texinfo 7.2 pl5321hf847389_0
    - zstd 1.5.7 h8210216_2
  host:
    - __osx >=11.0
  run:
    - __osx >=11.0
test:
  commands:
    - test -e $PREFIX/lib/libffi${SHLIB_EXT}
    - test -e $PREFIX/lib/libffi.a
    - test -e $PREFIX/include/ffi.h
    - test -e $PREFIX/include/ffitarget.h
  requires: null
about:
  description: 'The libffi library provides a portable, high level programming interface

    to various calling conventions. This allows a programmer to call any

    function specified by a call interface description at run-time.

    '
  dev_url: https://github.com/libffi/libffi
  doc_url: https://sourceware.org/libffi/
  home: https://sourceware.org/libffi/
  license: MIT
  license_file: LICENSE
  summary: A Portable Foreign Function Interface Library.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250331.5.1
  recipe-maintainers:
    - isuruf
    - scopatz
    - stefan-balke
  remote_url: https://github.com/conda-forge/libffi-feedstock
  sha: 1105c826e22f4eb4ef5147621f839770764a85b2
