# This file created by conda-build 25.5.0
# ------------------------------------------------

package:
  name: python
  version: 3.12.11
source:
  - url: https://www.python.org/ftp/python/3.12.11/Python-3.12.11.tar.xz
    md5: 9613d56b90d0d0cfd19980c7e2956a06
    patches:
      - patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0002-Win32-Do-not-download-externals.patch
      - patches/0003-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0004-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0005-Unvendor-openssl.patch
      - patches/0006-Unvendor-sqlite3.patch
      - patches/0007-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0008-Doing-d1trimfile.patch
      - patches/0009-cross-compile-darwin.patch
      - patches/0010-Fix-TZPATH-on-windows.patch
      - patches/0011-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
      - patches/0012-Unvendor-bzip2.patch
      - patches/0013-Unvendor-libffi.patch
      - patches/0014-Unvendor-tcltk.patch
      - patches/0015-unvendor-xz.patch
      - patches/0016-unvendor-zlib.patch
      - patches/0017-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
      - patches/0018-Unvendor-expat.patch
      - patches/0019-Remove-unused-readelf.patch
      - patches/0020-Don-t-checksharedmods-if-cross-compiling.patch
      - patches/0021-Override-configure-LIBFFI.patch
      - patches/0022-Allow-linking-ncursesw-panelw-on-macOS-if-available.patch
      - patches/0023-Do-not-define-pid_t-as-it-might-conflict-with-the-ac.patch
build:
  number: 0
  activate_in_script: true
  no_link: null
  ignore_run_exports_from:
    - clangxx_osx-arm64 18.*
    - xorg-libx11
    - xorg-xorgproto
  detect_binary_files_with_prefix: true
  skip_compile_pyc:
    - '*.py'
  string: hc22306f_0_cpython
  run_exports:
    noarch:
      - python
    weak:
      - python_abi 3.12.* *_cp312
  script_env:
    - CONDA_FORGE=yes
    - PY_INTERP_DEBUG=no
    - PY_INTERP_LINKAGE_NATURE=static
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - ca-certificates 2025.4.26 hbd8a1cb_0
    - cctools_osx-64 1010.6 hd19c6af_6
    - cctools_osx-arm64 1010.6 hd9414f1_6
    - clang 18.1.8 default_h576c50e_10
    - clang-18 18.1.8 default_h3571c67_10
    - clang_impl_osx-arm64 18.1.8 hadf8e89_25
    - clang_osx-arm64 18.1.8 h1728699_25
    - clangxx 18.1.8 default_heb2e8d1_10
    - clangxx_impl_osx-arm64 18.1.8 hd2305f4_25
    - clangxx_osx-arm64 18.1.8 h1728699_25
    - compiler-rt 18.1.8 h1020d70_1
    - compiler-rt_osx-64 18.1.8 hf2b8a54_1
    - expat 2.7.0 h240833e_0
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 951.9 h33512f0_6
    - ld64_osx-arm64 951.9 h0ae773b_6
    - libclang-cpp18.1 18.1.8 default_h3571c67_10
    - libcxx 20.1.6 hf95d169_0
    - libcxx-devel 18.1.8 h7c275be_8
    - libexpat 2.7.0 h240833e_0
    - libffi 3.4.6 h281671d_1
    - libiconv 1.18 h4b5e92a_1
    - libllvm18 18.1.8 default_h3571c67_5
    - libltdl 2.4.3a h240833e_0
    - liblzma 5.8.1 hd471939_1
    - liblzma-devel 5.8.1 hd471939_1
    - libsqlite 3.50.0 hdb6dae5_0
    - libtool 2.5.4 h240833e_0
    - libxml2 2.14.3 h8c082e5_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 18.1.8 default_h3571c67_5
    - llvm-tools-18 18.1.8 default_h3571c67_5
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.5.0 hc426f3f_1
    - pkg-config 0.29.2 hf7e621a_1009
    - readline 8.2 h7cca4af_2
    - sigtool 0.1.3 h88f4db0_0
    - sqlite 3.50.0 h2e4c9dc_0
    - tapi 1300.6.5 h390ca13_0
    - tk 8.6.13 hf689a15_2
    - zlib 1.3.1 hd23fc13_2
    - zstd 1.5.7 h8210216_2
  host:
    - bzip2 1.0.8 h99b78c6_7
    - ca-certificates 2025.4.26 hbd8a1cb_0
    - expat 2.7.0 h286801f_0
    - libexpat 2.7.0 h286801f_0
    - libffi 3.4.6 h1da3d7d_1
    - liblzma 5.8.1 h39f12f2_1
    - liblzma-devel 5.8.1 h39f12f2_1
    - libsqlite 3.50.0 h3f77e49_0
    - libxcb 1.17.0 hdb1d25a_0
    - libzlib 1.3.1 h8359307_2
    - ncurses 6.5 h5e97a16_3
    - openssl 3.5.0 h81ee809_1
    - pthread-stubs 0.4 hd74edd7_1002
    - readline 8.2 h1d1bf99_2
    - sqlite 3.50.0 hd7222ec_0
    - tk 8.6.13 h892fb3f_2
    - xorg-libx11 1.8.12 h6a5fb8c_0
    - xorg-libxau 1.0.12 h5505292_0
    - xorg-libxdmcp 1.1.5 hd74edd7_0
    - xorg-xorgproto 2024.1 hd74edd7_1
    - zlib 1.3.1 h8359307_2
  run:
    - __osx >=11.0
    - bzip2 >=1.0.8,<2.0a0
    - libexpat >=2.7.0,<3.0a0
    - libffi >=3.4.6,<3.5.0a0
    - liblzma >=5.8.1,<6.0a0
    - libsqlite >=3.50.0,<4.0a0
    - libzlib >=1.3.1,<2.0a0
    - ncurses >=6.5,<7.0a0
    - openssl >=3.5.0,<4.0a0
    - readline >=8.2,<9.0a0
    - tk >=8.6.13,<8.7.0a0
    - tzdata
  run_constrained:
    - python_abi 3.12.* *_cp312
test:
  downstreams:
    - cython
    - setuptools
  requires:
    - clang_osx-arm64 18.*
    - clangxx_osx-arm64 18.*
    - cmake
    - ninja
    - ripgrep
  files:
    - run_test.py
    - tests/cmake/*
    - tests/cython/*
    - tests/prefix-replacement/*
  commands:
    - python -V
    - python3 -V
    - 2to3 -h
    - pydoc -h
    - python3-config --help
    - python -c "from zoneinfo import ZoneInfo; from datetime import datetime; dt
      = datetime(2020, 10, 31, 12, tzinfo=ZoneInfo('America/Los_Angeles')); print(dt.tzname())"
    - python -m venv test-venv
    - test-venv/bin/python -c "import ctypes"
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - for f in ${CONDA_PREFIX}/lib/python*/_sysconfig*.py; do echo "Checking $f:";
      if [[ `rg @[^@]*@ $f` ]]; then echo "FAILED ON $f"; cat $f; exit 1; fi; done
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.a
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.nolto.a
    - pushd tests
    - pushd prefix-replacement
    - bash build-and-test.sh
    - popd
    - pushd cmake
    - cmake -GNinja -DPY_VER=3.12.11
    - popd
    - popd
    - python run_test.py
    - test ! -f default.profraw
    - test -d "$PREFIX/lib/python3.1/site-packages"
    - python3.1 --version
    - python -c "from ctypes import CFUNCTYPE; CFUNCTYPE(None)(id)"
    - TERM=xterm >/dev/null python -c "import curses; scr = curses.initscr(); curses.unget_wch('x');
      assert 'x' ==  scr.get_wch()"
    - python -c "import crypt"
about:
  home: https://www.python.org/
  license: Python-2.0
  license_file: LICENSE
  summary: General purpose programming language
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  doc_url: https://www.python.org/doc/versions/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  dev_url: https://docs.python.org/devguide/
extra:
  feedstock-name: python
  recipe-maintainers:
    - chrisburr
    - isuruf
    - jakirkham
    - katietz
    - mbargull
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
    - xhochy
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250604.1.1
  remote_url: https://github.com/conda-forge/python-feedstock
  sha: 51d2c9a1cdc63aeb30afb994e6a2924acc393084
