# This file created by conda-build 25.3.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jul 14 11:40:29 2025
# ------------------------------------------------

package:
  name: certifi
  version: 2025.7.14
source:
  - folder: certifi
    sha256: 8ea99dbdfaaf2ba2f9bac77b9249ef62ec5218e7c2b2e903378ed5fccf765995
    url: https://pypi.org/packages/source/c/certifi/certifi-2025.7.14.tar.gz
  - folder: boostrap_wheels
    sha256: c46efd13b6aa8279f33f2864459c8ce587ea6a1a59ee20de055868d8f7688f7f
    url: https://pypi.org/packages/py3/p/pip/pip-25.0.1-py3-none-any.whl
  - folder: boostrap_wheels
    sha256: e3982f444617239225d675215d51f6ba05f845d4eec313da4418fdbb56fb27e3
    url: https://pypi.org/packages/py3/s/setuptools/setuptools-75.8.0-py3-none-any.whl
  - folder: boostrap_wheels
    sha256: 708e7481cc80179af0e556bbf0cc00b8444c7321e2700b8d8580231d13017248
    url: https://pypi.org/packages/py3/w/wheel/wheel-0.45.1-py3-none-any.whl
build:
  noarch: python
  number: '0'
  script:
    - cd certifi
    - /home/conda/feedstock_root/build_artifacts/certifi_1752493286596/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
      -m pip install . -vv
  script_env:
    - 'PYTHONPATH=/home/conda/feedstock_root/build_artifacts/certifi_1752493286596/work/boostrap_wheels:'
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2025.7.14 hbd8a1cb_0
    - icu 75.1 he02047a_0
    - ld_impl_linux-64 2.44 h1423503_1
    - libexpat 2.7.0 h5888daf_0
    - libffi 3.4.6 h2dba641_1
    - libgcc 15.1.0 h767d61c_3
    - libgcc-ng 15.1.0 h69a702a_3
    - libgomp 15.1.0 h767d61c_3
    - liblzma 5.8.1 hb9d3cd8_2
    - libnsl 2.0.1 hb9d3cd8_1
    - libsqlite 3.50.2 hee844dc_2
    - libstdcxx 15.1.0 h8f9b012_3
    - libstdcxx-ng 15.1.0 h4852527_3
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.1 h7b32b05_0
    - python 3.9.23 hc30ae73_0_cpython
    - readline 8.2 h8c095d6_2
    - tk 8.6.13 noxft_hd72426e_102
    - tzdata 2025b h78e105d_0
  run:
    - python >=3.9
test:
  imports:
    - certifi
  requires:
    - python 3.9.*
about:
  description: 'Certifi is a curated collection of Root Certificates for validating
    the

    trustworthiness of SSL certificates while verifying the identity of TLS

    hosts.

    '
  dev_url: https://github.com/certifi/python-certifi
  doc_source_url: https://github.com/certifi/certifi.io/blob/master/README.rst
  doc_url: https://pypi.python.org/pypi/certifi
  home: http://certifi.io/
  license: ISC
  license_file: certifi/LICENSE
  summary: Python package for providing Mozilla's CA Bundle.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250714.4.1
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - pelson
    - sigmavirus24
  remote_url: https://github.com/conda-forge/certifi-feedstock
  sha: dca6a8959f75a821db67c803b71dfedbc1d1b82a
