# This file created by conda-build 25.4.2
# ------------------------------------------------

package:
  name: libarchive
  version: 3.7.7
source:
  patches:
    - patches/0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
  sha256: fa62384995e8aa4f5a901c184fb5c91e56a29e24c05b6881a7f8fd5bbea694d2
  url: https://github.com/libarchive/libarchive/archive/v3.7.7.tar.gz
build:
  number: 4
  run_exports:
    - libarchive >=3.7.7,<3.8.0a0
  string: h3c2f2b0_4
requirements:
  build:
    - autoconf 2.71 pl5321hed12c24_1
    - automake 1.17 pl5321h694c41f_0
    - ca-certificates 2025.1.31 hbd8a1cb_1
    - cctools_osx-64 1010.6 hd19c6af_6
    - cctools_osx-arm64 1010.6 hd9414f1_6
    - clang 18.1.8 default_h576c50e_9
    - clang-18 18.1.8 default_h3571c67_9
    - clang_impl_osx-arm64 18.1.8 hadf8e89_24
    - clang_osx-arm64 18.1.8 h1728699_24
    - clangxx 18.1.8 default_heb2e8d1_9
    - compiler-rt 18.1.8 h1020d70_1
    - compiler-rt_osx-64 18.1.8 hf2b8a54_1
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 951.9 h33512f0_6
    - ld64_osx-arm64 951.9 h0ae773b_6
    - libclang-cpp18.1 18.1.8 default_h3571c67_9
    - libcxx 20.1.3 hf95d169_0
    - libcxx-devel 18.1.8 h7c275be_8
    - libiconv 1.18 h4b5e92a_1
    - libllvm18 18.1.8 default_h3571c67_5
    - libltdl 2.4.3a h240833e_0
    - liblzma 5.8.1 hd471939_0
    - libtool 2.5.4 h240833e_0
    - libxml2 2.14.2 h8c082e5_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 18.1.8 default_h3571c67_5
    - llvm-tools-18 18.1.8 default_h3571c67_5
    - m4 1.4.18 haf1e3a3_1001
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.5.0 hc426f3f_0
    - perl 5.32.1 7_h10d778d_perl5
    - pkg-config 0.29.2 hf7e621a_1009
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.7 h8210216_2
  host:
    - bzip2 1.0.8 h99b78c6_7
    - ca-certificates 2025.1.31 hbd8a1cb_1
    - icu 75.1 hfee45f7_0
    - libcxx 20.1.3 ha82da77_0
    - libiconv 1.18 hfe07756_1
    - liblzma 5.8.1 h39f12f2_0
    - liblzma-devel 5.8.1 h39f12f2_0
    - libxml2 2.13.7 h52572c6_1
    - libzlib 1.3.1 h8359307_2
    - lz4-c 1.10.0 h286801f_1
    - lzo 2.10 h93a5062_1001
    - openssl 3.5.0 h81ee809_0
    - zlib 1.3.1 h8359307_2
    - zstd 1.5.7 h6491c7d_2
  run:
    - __osx >=11.0
    - bzip2 >=1.0.8,<2.0a0
    - libiconv >=1.18,<2.0a0
    - liblzma >=5.8.1,<6.0a0
    - libxml2 >=2.13.7,<2.14.0a0
    - libzlib >=1.3.1,<2.0a0
    - lz4-c >=1.10.0,<1.11.0a0
    - lzo >=2.10,<3.0a0
    - openssl >=3.5.0,<4.0a0
    - zstd >=1.5.7,<1.6.0a0
test:
  commands:
    - test -f "${PREFIX}/lib/pkgconfig/libarchive.pc"
    - test -f "${PREFIX}/include/archive.h"
    - test -f "${PREFIX}/include/archive_entry.h"
    - test -f "${PREFIX}/lib/libarchive.a"
    - test -f "${PREFIX}/lib/libarchive${SHLIB_EXT}"
    - bsdcat --version
    - bsdcpio --version
    - bsdtar --version
    - bsdtar -tf test/hello_world.xar
  files:
    - test/hello_world.xar
about:
  home: http://www.libarchive.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING
  summary: Multi-format archive and compression library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250422.4.1
  recipe-maintainers:
    - jakirkham
    - jjerphan
    - ocefpaf
  remote_url: https://github.com/conda-forge/libarchive-feedstock
  sha: 6f3175ad2a16c6ee5909aa563bda12e99b7dc1b0
