# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Mar 24 16:17:43 2025
# ------------------------------------------------

package:
  name: fmt
  version: 11.1.4
source:
  sha256: ac366b7b4c2e9f0dde63a59b3feb5ee59b67974b14ee5dc9ea8ad78aa2c1ee1e
  url: https://github.com/fmtlib/fmt/archive/11.1.4.tar.gz
build:
  number: '1'
  run_exports:
    - fmt >=11.1.4,<11.2.0a0
  string: h440487c_1
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - c-ares 1.34.4 hf13058a_0
    - ca-certificates 2025.1.31 h8857fd0_0
    - cctools_osx-64 1010.6 hd19c6af_4
    - cctools_osx-arm64 1010.6 hd9414f1_4
    - clang 18.1.8 default_h576c50e_8
    - clang-18 18.1.8 default_h3571c67_8
    - clang_impl_osx-arm64 18.1.8 hadf8e89_24
    - clang_osx-arm64 18.1.8 h1728699_24
    - clangxx 18.1.8 default_heb2e8d1_8
    - clangxx_impl_osx-arm64 18.1.8 hd2305f4_24
    - clangxx_osx-arm64 18.1.8 h1728699_24
    - cmake 3.31.6 h477996e_0
    - compiler-rt 18.1.8 h1020d70_1
    - compiler-rt_osx-64 18.1.8 hf2b8a54_1
    - krb5 1.21.3 h37d8d59_0
    - ld64_osx-64 951.9 h33512f0_4
    - ld64_osx-arm64 951.9 h0ae773b_4
    - libclang-cpp18.1 18.1.8 default_h3571c67_8
    - libcurl 8.12.1 h5dec5d8_0
    - libcxx 20.1.1 hf95d169_0
    - libcxx-devel 18.1.8 h7c275be_8
    - libedit 3.1.20250104 pl5321ha958ccf_0
    - libev 4.33 h10d778d_2
    - libexpat 2.6.4 h240833e_0
    - libiconv 1.18 h4b5e92a_1
    - libllvm18 18.1.8 hc29ff6c_3
    - liblzma 5.6.4 hd471939_0
    - libnghttp2 1.64.0 hc7306c3_0
    - libssh2 1.11.1 h3dc7d44_0
    - libuv 1.50.0 h4cb831e_0
    - libxml2 2.13.6 he8ee3e7_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 18.1.8 hc29ff6c_3
    - llvm-tools-18 18.1.8 hc29ff6c_3
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.4.1 hc426f3f_0
    - rhash 1.4.5 ha44c9a9_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.7 h8210216_2
  host:
    - libcxx 20.1.1 ha82da77_0
  run:
    - __osx >=11.0
    - libcxx >=18
test:
  commands:
    - test -d ${PREFIX}/include/fmt
    - test -f ${PREFIX}/include/fmt/core.h
    - test -f ${PREFIX}/include/fmt/format.h
    - test -f ${PREFIX}/lib/cmake/fmt/fmt-config.cmake
    - test -f ${PREFIX}/lib/libfmt.dylib
  downstreams:
    - libmambapy
about:
  description: '{fmt} is an open-source formatting library for C++.

    It can be used as a safe and fast alternative to (s)printf and iostreams.

    '
  dev_url: https://github.com/fmtlib/fmt
  doc_url: https://fmt.dev/latest/
  home: https://fmt.dev/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: '{fmt} is an open-source formatting library for C++'
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250324.1.1
  recipe-maintainers:
    - bdice
    - h-vetinari
    - saraedum
    - tdegeus
    - vitaut
  remote_url: https://github.com/conda-forge/fmt-feedstock
  sha: d8e72658ff8dd4689bd62e6f47925565d00dd3f0
