# This file created by conda-build 25.1.2
# ------------------------------------------------

package:
  name: zstd
  version: 1.5.7
source:
  sha256: 37d7284556b20954e56e1ca85b80226768902e2edabd3b649e9e72c0c9012ee3
  url: https://github.com/facebook/zstd/archive/v1.5.7.tar.gz
build:
  number: 2
  run_exports:
    - zstd >=1.5.7,<1.6.0a0
  string: h6491c7d_2
requirements:
  build:
    - clang_bootstrap_osx-arm64 18.1.8 hf1725c4_23
    - cmake-no-system 3.31.6 hbcac03e_0
    - libcxx 19.1.7 hf95d169_0
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
    - ninja 1.12.1 h3c5361c_0
  host:
    - libzlib 1.3.1 h8359307_2
    - zlib 1.3.1 h8359307_2
  run:
    - __osx >=11.0
    - libzlib >=1.3.1,<2.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libzstd.dylib
    - test ! -f ${PREFIX}/lib/libzstd.a
    - test -f ${PREFIX}/include/zstd.h
    - zstd -be -i5
    - test -f ${PREFIX}/lib/pkgconfig/libzstd.pc
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
    - pkg-config --cflags libzstd
    - cd cf_test
  files:
    - cf_test/
  requires:
    - clang_bootstrap_osx-arm64 18.*
    - cmake
    - make
    - pkg-config
about:
  description: 'Zstandard is a real-time compression algorithm, providing high compression

    ratios. It offers a very wide range of compression / speed trade-off, while

    being backed by a very fast decoder. It also offers a special mode for

    small data, called dictionary compression, and can create dictionaries from

    any sample set. Zstandard library is provided as open source software using

    a BSD license.

    '
  dev_url: https://github.com/facebook/zstd
  doc_url: https://facebook.github.io/zstd/zstd_manual.html
  home: http://www.zstd.net
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Zstandard - Fast real-time compression algorithm
extra:
  copy_test_source_files: true
  feedstock-name: zstd
  final: true
  flow_run_id: azure_20250319.1.1
  recipe-maintainers:
    - JohanMabille
    - hmaarrfk
    - msarahan
    - rmax
    - xhochy
  remote_url: https://github.com/conda-forge/zstd-feedstock
  sha: 93b16964779c72e6ae2654734a553255c4e1aab3
