# This file created by conda-build 25.5.0
# ------------------------------------------------

package:
  name: brotli-python
  version: 1.1.0
source:
  fn: brotli-1.1.0.tar.gz
  url: https://github.com/google/brotli/archive/v1.1.0.tar.gz
  sha256: e720a6ca29428b803f4ad165371771f5398faba397edf6778837a18599ea13ff
build:
  ignore_run_exports_from:
    - brotli
  number: 3
  string: py312hd8f9ff3_3
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - c-ares 1.34.5 hf13058a_0
    - ca-certificates 2025.4.26 hbd8a1cb_0
    - cctools_osx-64 1010.6 hd19c6af_6
    - cctools_osx-arm64 1010.6 hd9414f1_6
    - clang 18.1.8 default_h576c50e_10
    - clang-18 18.1.8 default_h3571c67_10
    - clang_impl_osx-arm64 18.1.8 hadf8e89_25
    - clang_osx-arm64 18.1.8 h1728699_25
    - clangxx 18.1.8 default_heb2e8d1_10
    - clangxx_impl_osx-arm64 18.1.8 hd2305f4_25
    - clangxx_osx-arm64 18.1.8 h1728699_25
    - cmake 4.0.2 h477996e_0
    - compiler-rt 18.1.8 h1020d70_1
    - compiler-rt_osx-64 18.1.8 hf2b8a54_1
    - cross-python_osx-arm64 3.12 51_cpython
    - crossenv 1.5.0 pyhd8ed1ab_1
    - icu 75.1 h120a0e1_0
    - krb5 1.21.3 h37d8d59_0
    - ld64_osx-64 951.9 h33512f0_6
    - ld64_osx-arm64 951.9 h0ae773b_6
    - libclang-cpp18.1 18.1.8 default_h3571c67_10
    - libcurl 8.14.1 h5dec5d8_0
    - libcxx 20.1.6 hf95d169_0
    - libcxx-devel 18.1.8 h7c275be_8
    - libedit 3.1.20250104 pl5321ha958ccf_0
    - libev 4.33 h10d778d_2
    - libexpat 2.7.0 h240833e_0
    - libffi 3.4.6 h281671d_1
    - libiconv 1.18 h4b5e92a_1
    - libintl 0.24.1 h27064b9_0
    - libllvm18 18.1.8 default_h3571c67_5
    - liblzma 5.8.1 hd471939_1
    - libnghttp2 1.64.0 hc7306c3_0
    - libsqlite 3.50.0 hdb6dae5_0
    - libssh2 1.11.1 hed3591d_0
    - libuv 1.51.0 h4cb831e_0
    - libxml2 2.14.3 h8c082e5_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 18.1.8 default_h3571c67_5
    - llvm-tools-18 18.1.8 default_h3571c67_5
    - lz4-c 1.10.0 h240833e_1
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - ncurses 6.5 h0622a9a_3
    - ninja 1.12.1 hd6aca1a_1
    - openssl 3.5.0 hc426f3f_1
    - popt 1.16 h7b079dc_2002
    - python 3.12.11 h9ccd52b_0_cpython
    - readline 8.2 h7cca4af_2
    - rhash 1.4.5 ha44c9a9_0
    - rsync 3.4.1 hf2bfba0_2
    - sed 4.9 hf9b2955_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - tk 8.6.13 hf689a15_2
    - tzdata 2025b h78e105d_0
    - xxhash 0.8.3 h13e91ac_0
    - zstd 1.5.7 h8210216_2
  host:
    - brotli 1.1.0 h5505292_3
    - bzip2 1.0.8 h99b78c6_7
    - ca-certificates 2025.4.26 hbd8a1cb_0
    - libcxx 20.1.6 ha82da77_0
    - libexpat 2.7.0 h286801f_0
    - libffi 3.4.6 h1da3d7d_1
    - liblzma 5.8.1 h39f12f2_1
    - libsqlite 3.50.0 h3f77e49_0
    - libzlib 1.3.1 h8359307_2
    - ncurses 6.5 h5e97a16_3
    - openssl 3.5.0 h81ee809_1
    - pip 25.1.1 pyh8b19718_0
    - python 3.12.11 hc22306f_0_cpython
    - readline 8.2 h1d1bf99_2
    - setuptools 80.9.0 pyhff2d567_0
    - tk 8.6.13 h892fb3f_2
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - __osx >=11.0
    - libcxx >=18
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
  run_constrained:
    - libbrotlicommon 1.1.0 h5505292_3
test:
  imports:
    - brotli
about:
  home: http://github.com/google/brotli
  dev_url: http://github.com/google/brotli
  license: MIT
  license_file: LICENSE
  summary: Brotli compression format
extra:
  recipe-maintainers:
    - CJ-Wright
    - wesm
    - xhochy
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250606.2.1
  remote_url: https://github.com/conda-forge/brotli-feedstock
  sha: 3b307fa1233138d5bca196a05d1a20d1c400baf3
