# This file created by conda-build 25.5.0
# ------------------------------------------------

package:
  name: libexpat
  version: 2.7.1
source:
  url: https://github.com/libexpat/libexpat/releases/download/R_2_7_1/expat-2.7.1.tar.bz2
  sha256: 45c98ae1e9b5127325d25186cf8c511fa814078e9efeae7987a574b482b79b3d
build:
  ignore_run_exports_from:
    - clangxx_osx-arm64 19.*
  number: 0
  string: hec049ff_0
requirements:
  build:
    - ca-certificates 2025.7.14 hbd8a1cb_0
    - cctools_osx-64 1010.6 h96393e6_6
    - cctools_osx-arm64 1010.6 h4c96acc_6
    - clang 19.1.7 default_h576c50e_3
    - clang-19 19.1.7 default_h3571c67_3
    - clang_impl_osx-arm64 19.1.7 h4fa02b8_25
    - clang_osx-arm64 19.1.7 h1728699_25
    - clangxx 19.1.7 default_heb2e8d1_3
    - clangxx_impl_osx-arm64 19.1.7 hd0141c2_25
    - clangxx_osx-arm64 19.1.7 h1728699_25
    - compiler-rt 19.1.7 h52031e2_0
    - compiler-rt_osx-64 19.1.7 hc6f8467_0
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 951.9 h5ab288c_6
    - ld64_osx-arm64 951.9 h6674ee5_6
    - libclang-cpp19.1 19.1.7 default_h3571c67_3
    - libcxx 20.1.8 hf95d169_0
    - libcxx-devel 19.1.7 h7c275be_1
    - libiconv 1.18 h4b5e92a_1
    - libllvm19 19.1.7 hc29ff6c_1
    - liblzma 5.8.1 hd471939_2
    - libxml2 2.13.8 h93c44a6_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 19.1.7 h3fe3016_1
    - llvm-tools-19 19.1.7 he90a8e3_1
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.5.1 hc426f3f_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.7 h8210216_2
  run_constrained:
    - expat 2.7.1.*
  host:
    - __osx >=11.0
  run:
    - __osx >=11.0
test: {}
about:
  home: http://expat.sourceforge.net/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Expat XML parser library in C
extra:
  feedstock-name: expat
  recipe-maintainers:
    - isuruf
    - kwilcox
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250716.4.1
  remote_url: https://github.com/conda-forge/expat-feedstock
  sha: 6178cd15d555c99dc1be92f6f3a018a7d22fa666
